// To experiment with error handling , "threshold" values cause errors randomly

const THRESHOLD_A = 8; 

function tetheredGetNumber(resolve, reject) {
    setTimeout(() => {
        
    })
}